name: Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Gradle
        run: ./gradlew test
      - name: Dashboard
        uses: test-summary/action@v2.4
        with:
          paths: "build/test-results/test/TEST-*.xml"
        if: always()
